import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/utils/theme-provider";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "xoboid - decoding signals from the void",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="mx-auto flex min-h-screen max-w-[872px] flex-col gap-9px-10 py-8 text-sm md:gap-20 md:py-16 ">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
				>
					<Header />
					<div className={inter.className}>{children}</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
